slackapikey: <SLACK_API_KEY>
slackchannel: "#test"
delayreport: 30 # minute
delaycheck: 1 # minute
worker: 5
timezone: Asia/Jakarta

urls:
  - https://www.google.com
  - https://github.com
  - https://gitlab.com
